### ISSUE TITLE
partial tcl file

### ISSUE THREAD

**Issue by royforu** [byuccl/PYNQ-PRIO#1]
Hi,
May I ask how can I create partial tcl file such as gpio.tcl, iic.tcl, uart.tcl, led_pattern.tcl in this project.
It seems that partial tcl file must be created first so that i can use them in create_pr.tcl. 
Thanks for your kindly help.

**Comment by hcook95** [comment]
Sorry for the late reply!

We used a flow that utilized block diagrams in Vivado. Once a block diagram has been created in Vivado and has ports that match the partial region, then use the command `write_bd_tcl <file_name>` to produce the partial tcl file. 

Hope this helps! I'm closing this issue for now. Reopen it if you need further clarification.

**Comment by royforu** [comment]
Thanks for your reply.  you don't need to say sorry. Something i did lately just like you did was to use block diagram in vivado. Maybe we use the same method. 
Thanks~~
